services:
  - type: web
    name: visa-ctrl-canada
    region: Oregon
    env: python
    buildCommand: rm -rf /opt/render/.cache/ms-playwright && pip install --upgrade pip greenlet playwright flask certifi charset-normalizer idna pyee python-dateutil python-dotenv requests six typing_extensions urllib3 waitress resend python-telegram-bot && python -m playwright install chromium
    startCommand: cd canada && python -m waitress --port=$PORT --host=0.0.0.0 app:app
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: PORT
        value: "8080"
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false